#Executaveis
PLAY=play
PLAY_DEPENDENCIES=$(SOURCE_FOLDER)/$(WINDOW:=.o) $(SOURCE_FOLDER)/$(RECTANGLE:=.o) $(SOURCE_FOLDER)/$(IMAGE:=.o) $(SOURCE_FOLDER)/$(TEXT:=.o) $(SOURCE_FOLDER)/$(BUTTON:=.o) $(SOURCE_FOLDER)/$(TEXT_BOX:=.o) $(SOURCE_FOLDER)/$(RECTANGLE_CONTROLLER:=.o) 




#Arquivos
INCLUDES=Includes
WINDOW=Window
ANIMATION=Animation
IMAGE=Image
MAIN=Main
#PLAYER=Player
RECTANGLE=Rectangle
BUTTON=Button
TEXT=Text
TEXT_BOX=TextBox

#CONTROLADORES
CONTROLLER=Controller
RECTANGLE_CONTROLLER=RectangleController

#Pastas
SOURCE_FOLDER=src

#Compilador
CC=g++
#CC=gcc

#Linkers
LINKERS=-lSDL2 -lSDL2_ttf -lSDL2_image -lpthread

#Executor
EXECUTE=./

#Otimizador
# OPTIMIZE=-o3

#Opções
#USE_ANSI=-ansi
#USE_ANSI=-std=c++11
#LIKE_A_LIBRARY=-c
LIKE_A_LIBRARY=-c
LIKE_A_EXECUTABLE=-o

#Comandos
OPEN_FOLDER=cd
REMOVE=rm
DEBUGGER=valgrind
DEBUG_SUPPORT=-g


################################################EXECUTABLES COMPILATION

all: $(PLAY_DEPENDENCIES)
	$(CC) $(USE_ANSI) $(SOURCE_FOLDER)/$(MAIN:=.cpp) $(PLAY_DEPENDENCIES) $(OPTIMIZE) $(LIKE_A_EXECUTABLE) $(PLAY) $(LINKERS)
#	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(USE_ANSI) $(MAIN:=.cpp) $(PLAY_DEPENDENCIES) $(OPTIMIZE) $(LIKE_A_EXECUTABLE) ../$(PLAY) $(LINKERS)

debug: $(PLAY_DEPENDENCIES)
	$(CC) $(USE_ANSI) $(SOURCE_FOLDER)/$(MAIN:=.cpp) $(PLAY_DEPENDENCIES) $(DEBUG_SUPPORT) $(OPTIMIZE) $(LIKE_A_EXECUTABLE)  $(PLAY) $(LINKERS)
#	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(USE_ANSI) $(MAIN:=.cpp) $(PLAY_DEPENDENCIES) $(OPTIMIZE) $(LIKE_A_EXECUTABLE) $(DEBUG_SUPPORT) ../$(PLAY) $(LINKERS)
# all: $(PLAY_DEPENDENCIES)
# 	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(USE_ANSI) $(MAIN:=.cpp) $(PLAY_DEPENDENCIES:=.o) $(OPTIMIZE) $(LIKE_A_EXECUTABLE) ../$(PLAY) $(LINKERS)
# 	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(REMOVE) $(PLAY_DEPENDENCIES:=.o)



##############################################LIBRARIES COMPILATION
#$(SCREEN:=.o):
# $(SCREEN):
# 	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(SCREEN)/$(SCREEN:=.cpp)


#$(RECTANGLE:=.o):
#$(RECTANGLE): $(WINDOW)

$(SOURCE_FOLDER)/$(RECTANGLE:=.o):
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(RECTANGLE)/$(RECTANGLE:=.cpp)

$(SOURCE_FOLDER)/$(RECTANGLE_CONTROLLER:=.o): $(SOURCE_FOLDER)/$(WINDOW:=.o) $(SOURCE_FOLDER)/$(RECTANGLE:=.o)
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(CONTROLLER)/$(RECTANGLE_CONTROLLER:=.cpp)


$(SOURCE_FOLDER)/$(TEXT:=.o): $(SOURCE_FOLDER)/$(WINDOW:=.o)
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(TEXT)/$(TEXT:=.cpp)

$(SOURCE_FOLDER)/$(BUTTON:=.o): $(SOURCE_FOLDER)/$(WINDOW:=.o) $(SOURCE_FOLDER)/$(TEXT:=.o) $(SOURCE_FOLDER)/$(RECTANGLE:=.o)
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(BUTTON)/$(BUTTON:=.cpp)
	
$(SOURCE_FOLDER)/$(IMAGE:=.o): $(SOURCE_FOLDER)/$(WINDOW:=.o)
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(IMAGE)/$(IMAGE:=.cpp)

$(SOURCE_FOLDER)/$(TEXT_BOX:=.o): $(SOURCE_FOLDER)/$(WINDOW:=.o) $(SOURCE_FOLDER)/$(TEXT:=.o) $(SOURCE_FOLDER)/$(BUTTON:=.o)
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(TEXT_BOX)/$(TEXT_BOX:=.cpp)

# $(ANIMATION): $(SCREEN:=.o) $(IMAGE:=.o)
# 	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(ANIMATION)/$(ANIMATION:=.cpp)


$(SOURCE_FOLDER)/$(WINDOW:=.o):
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(CC) $(LIKE_A_LIBRARY) $(USE_ANSI) $(WINDOW)/$(WINDOW:=.cpp)

#Run
run:
	$(EXECUTE)$(PLAY)

#Debug
#debug:
#	$(DEBUGGER) $(EXECUTE)$(PLAY)

#Clean
clean:
	$(OPEN_FOLDER) $(SOURCE_FOLDER); $(REMOVE) *.o




